name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
            git remote set-url origin https://lumosGolem:$HF_TOKEN@huggingface.co/spaces/lumosGolem/agents_book_club
            git reset
            git rm --cached design-faq/book_store/book_case/index.faiss
            git add .
            git commit -m "Your commit message without the large file"
            git push --force origin main
